project:
  type: website
  output-dir: _site

website:
  site-url: "https://jordanchongja.github.io"
  title: "Jordan's Projects"
  open-graph:
    image: "/assets/homepage-preview.png"
  twitter-card:
    image: homepage-preview.png
    card-style: summary_large_image
  image: "/assets/avatar.jpg"
  description: "Portfolio of Jordan Chong - Finance & Data Science"
  favicon: /assets/favicon.png
  google-analytics: "G-V7YLYPVKHH"
  
  navbar:
    background: "#f8f9fa"
    foreground: "#1a1a1a"
    left:
      # Removed "Home" - Clicking "Jordan Chong" works.
      - href: projects/index.qmd
        text: Projects
      - href: notes/index.qmd
        text: Notes
      - href: readings/index.qmd
        text: Readings
    right:
      # CV stays here as a "Utility" link
      - text: CV
        href: /assets/Jordan_Chong_CV.pdf
        target: _blank 
      - icon: linkedin
        href: https://www.linkedin.com/in/jordan-chong-88a02b172/
      - icon: github
        href: https://github.com/jordanchongja

  page-footer:
    left: |
      <span class="p-1">Made with <a href="https://quarto.org/">Quarto</a>.</span>
    center:
      - icon: github
        href: https://github.com/jordanchongja
      - icon: linkedin
        href: https://www.linkedin.com/in/jordan-chong-88a02b172/
      - icon: envelope
        href: "mailto:jordanchongjian25@gmail.com"
      - text: "|"
      - icon: github
        text: "Source"
        href: https://github.com/jordanchongja/jordanchongja.github.io
    right:
      - text: "License"
        href: license.qmd 
      - text: "Contact"
        href: contact.qmd 

  search: true

format:
  html:
    theme: cosmo
    css: styles.css # This links your new CSS file
    toc: true